spring.datasource.url=jdbc:mysql://quantumbill-quantumbill.l.aivencloud.com:13636/defaultdb?sslMode=REQUIRED&allowPublicKeyRetrieval=true

spring.datasource.username=${MYSQL_USERNAME:avnadmin}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ==========================
# MONGODB ATLAS
# ==========================
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DATABASE:quantumbill}
