spring.application.name=stock

spring.datasource.url=jdbc:mysql://quantumbill-quantumbill.l.aivencloud.com:25544/stock_simulator?sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=${AIVEN_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


